printWidth: 80
tabWidth: 2
singleQuote: false
trailingComma: none
bracketSpacing: true
semi: true
useTabs: false
proseWrap: preserve
arrowParens: avoid
htmlWhitespaceSensitivity: css
endOfLine: auto
quoteProps: as-needed
